language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
  - DEPOPTS=github
  - PINS="github"
  matrix:
  - OCAML_VERSION=4.02
  - OCAML_VERSION=4.03
os:
  - linux
  - osx
